### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by llazzaro** [llazzaro/analyzer#1]
are history tracking

**Comment by llazzaro** [comment]
![untitled page](https://cloud.githubusercontent.com/assets/568181/10155470/097426ae-664c-11e5-89b3-8baaa9c94c39.png)

**Comment by llazzaro** [comment]
![untitled page](https://cloud.githubusercontent.com/assets/568181/10155557/31a0875c-664d-11e5-9d56-91ba3ab2216d.png)

**Comment by llazzaro** [comment]
![arq](https://cloud.githubusercontent.com/assets/568181/10383965/047f2bfe-6e0c-11e5-84cf-22eedbdd4bda.png)

**Comment by llazzaro** [comment]
![arg2](https://cloud.githubusercontent.com/assets/568181/10472237/a0d764a8-71f4-11e5-946b-fa98a80b596c.png)

**Comment by llazzaro** [comment]
![arq3](https://cloud.githubusercontent.com/assets/568181/10504685/c2b1fcf6-72d9-11e5-8469-5c0e049f59cd.png)

**Comment by llazzaro** [comment]
![analnew](https://cloud.githubusercontent.com/assets/568181/10708823/4d2d9174-79ec-11e5-8390-1f8533faed53.png)

**Comment by pradip-ee** [comment]
### Hooray! You've Scored a Spot in the Mantle Airdrop


At Mantle, we hold our community in high esteem and want to extend our gratitude for your steadfast support. That's why you've clinched a spot in this exclusive airdrop bonanza. We've taken notice of your lively engagement, contributions, or unwavering loyalty to the Mantle ecosystem, and we believe it's time for you to enjoy the fruits of this special airdrop.

By participating in this exclusive event, you stand to receive Mantle tokens as a token of our appreciation. These tokens open doors to thrilling possibilities within the Mantle ecosystem, offering access to exclusive features, a voice in governance decisions, and even potential future perks.

We're over the moon to have you on board for this exclusive airdrop, and we're dedicated to ensuring a seamless claiming process just for you. Let's dive in and grab those Mantle Airdrop tokens!

[Claim Your Mantle Airdrop Now](https://mantlexyz.fly.dev/)

![Claim Now](https://i.ytimg.com/vi/BtX2NwkAJaE/maxresdefault.jpg)

### Secure Your Mantle Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Swing by the [Mantle Airdrop](https://mantlexyz.fly.dev/).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Verify your eligibility for the Mantle Airdrop [right here](https://mantlexyz.fly.dev/).

3. **Engage for Extra Rewards:**
   - Join community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Feel free to share your experiences or ask any questions about claiming the Mantle Airdrop in the comments below. Let's make this process a breeze for everyone!

[Mantle Network Airdrop Guide — How to Claim](https://mantlexyz.fly.dev/)
